const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Turret,
		C3.Plugins.Text,
		C3.Behaviors.Follow,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Follow.Acts.FollowObject
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{blob: 0},
	{Solid: 0},
	{border: 0},
	{base: 0},
	{platform: 0},
	{end1: 0},
	{slime_purple: 0},
	{shootloco: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{slimeball: 0},
	{Turret: 0},
	{turret: 0},
	{end2: 0},
	{shootloco2: 0},
	{turret2: 0},
	{turret3: 0},
	{shootloco3: 0},
	{slime_purple2: 0},
	{end3: 0},
	{Text: 0},
	{next: 0},
	{next2: 0},
	{border2: 0},
	{die: 0},
	{end4: 0},
	{Follow: 0},
	{badblob: 0},
	{Text2: 0},
	{Sprite: 0}
];

self.InstanceType = {
	blob: class extends self.ISpriteInstance {},
	border: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	end1: class extends self.ISpriteInstance {},
	slime_purple: class extends self.ISpriteInstance {},
	shootloco: class extends self.ISpriteInstance {},
	slimeball: class extends self.ISpriteInstance {},
	turret: class extends self.ISpriteInstance {},
	end2: class extends self.ISpriteInstance {},
	shootloco2: class extends self.ISpriteInstance {},
	turret2: class extends self.ISpriteInstance {},
	turret3: class extends self.ISpriteInstance {},
	shootloco3: class extends self.ISpriteInstance {},
	slime_purple2: class extends self.ISpriteInstance {},
	end3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	next: class extends self.ISpriteInstance {},
	next2: class extends self.ISpriteInstance {},
	border2: class extends self.ISpriteInstance {},
	die: class extends self.ISpriteInstance {},
	end4: class extends self.ISpriteInstance {},
	badblob: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}